server:
  port: 8080

spring:
  application:
    name: bapool

  datasource:
    platform: mysql
    url: #jdbc:mysql://localhost:3306/testDB
    username: root
    password: #비번 적어주세요
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8